# Generated by Django 5.0.14 on 2026-08-29 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=128)),
                ('asset_type', models.CharField(choices=[('Transformer', 'Transformer'), ('Battery', 'Battery'), ('Switchgear', 'Switchgear'), ('Pump', 'Pump'), ('Hospital', 'Hospital'), ('WaterPlant', 'WaterPlant')], max_length=32)),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('elevation', models.FloatField(default=0.0)),
                ('scada_link_id', models.CharField(max_length=64, unique=True)),
                ('replacement_cost', models.FloatField(default=0.0)),
                ('flood_zone', models.CharField(blank=True, default='', max_length=32)),
                ('age', models.IntegerField(default=20)),
                ('risk_score', models.FloatField(default=0.0)),
                ('confidence', models.FloatField(default=1.0)),
                ('conflict_flag', models.BooleanField(default=False)),
                ('drivers_json', models.JSONField(blank=True, default=list)),
            ],
            options={
                'ordering': ['external_id'],
            },
        ),
        migrations.CreateModel(
            name='Telemetry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('load', models.FloatField()),
                ('oil_temp', models.FloatField()),
                ('voltage', models.FloatField(default=120.0)),
                ('battery_voltage', models.FloatField(default=125.0)),
                ('is_anomaly', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telemetry', to='api.asset')),
            ],
            options={
                'verbose_name_plural': 'telemetry',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='WeatherContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('wind_speed', models.FloatField()),
                ('flood_surge_level', models.FloatField()),
                ('storm_category', models.CharField(blank=True, default='demo', max_length=32)),
                ('ambient_temp', models.FloatField(default=28.0)),
                ('asset', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='weather', to='api.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Dependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upstream_links', to='api.asset')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='downstream_links', to='api.asset')),
            ],
            options={
                'verbose_name_plural': 'dependencies',
                'unique_together': {('parent', 'child')},
            },
        ),
    ]
