# Generated by Django 5.0.14 on 2026-08-29 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(default='demo-ic', max_length=64)),
                ('action', models.CharField(max_length=64)),
                ('reason_text', models.TextField()),
                ('authorization_level', models.CharField(max_length=32)),
                ('ai_recommendation', models.CharField(blank=True, default='', max_length=64)),
                ('human_override', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('outcome', models.CharField(blank=True, default='', max_length=128)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='api.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ShadowLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ai_predicted_action', models.CharField(max_length=64)),
                ('human_actual_action', models.CharField(max_length=64)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shadow_logs', to='api.asset')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
